# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('byeWorld', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exemplo',
        ),
    ]
